spring:
  application:
    name: BootFluxApplication
  r2dbc:
    name: flux
    username: root
    password: root@123
    url: r2dbc:mysql://localhost:3306/
#  循环依赖问题
#  main:
#    allow-circular-references: true
server:
  port: 8888
